name: Run tests
on:
  push:
    paths:
      - 'examples/functions/configuration.ps1'
      - 'examples/tests/configuration.Tests.ps1'
  workflow_dispatch:

jobs:
  pester-test:
    name: Pester test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Perform Pester tests against the label configuration
        shell: pwsh
        run: |
          Invoke-Pester -Output Detailed .\examples\tests\configuration.Tests.ps1 -Passthru